In [127]:
# Import necessary libraries

import sklearn 
# Import the sklearn library for machine learning tools

from sklearn.utils import shuffle 
# Import shuffle to randomly mix up data

from sklearn.neighbors import KNeighborsClassifier 
# Import the K-Nearest Neighbors classifier

import pandas as pd 
# Import pandas for data handling

import numpy as np 
# Import NumPy for numerical operations

from sklearn import linear_model, preprocessing 
# Import linear models and tools for preprocessing data

from sklearn.metrics import confusion_matrix 
# Import confusion matrix to evaluate model errors

from sklearn.metrics import f1_score 
# Import F1 score to check model balance

from sklearn.metrics import accuracy_score 
# Import accuracy score to measure model correctness


In [128]:
#Loads the data from car data
data = pd.read_csv("car.data")
#Prints the first few lines of the data that was previously loaded
print (data.head())

  buying  maint doors persons lug_boot safety  class
0  vhigh  vhigh     2       2    small    low  unacc
1  vhigh  vhigh     2       2    small    med  unacc
2  vhigh  vhigh     2       2    small   high  unacc
3  vhigh  vhigh     2       2      med    low  unacc
4  vhigh  vhigh     2       2      med    med  unacc


In [129]:
le = preprocessing.LabelEncoder()
# Create a LabelEncoder to convert categorical text data into numbers

buying = le.fit_transform(list(data["buying"]))
# Convert the "buying" column's categories into numbers

maint = le.fit_transform(list(data["maint"]))
# Convert the "maint" (maintenance) column's categories into numbers

doors = le.fit_transform(list(data["doors"]))
# Convert the "doors" column's categories into numbers

persons = le.fit_transform(list(data["persons"]))
# Convert the "persons" column's categories into numbers

lug_boot = le.fit_transform(list(data["lug_boot"]))
# Convert the "lug_boot" (luggage boot) column's categories into numbers

safety = le.fit_transform(list(data["safety"]))
# Convert the "safety" column's categories into numbers

cls = le.fit_transform(list(data["class"]))
# Convert the "class" column's categories into numbers (the target variable)


In [130]:
predict = "class"
# Set the column "class" as the target variable you want to predict

In [131]:
x = list(zip(buying, maint, doors, persons, lug_boot, safety))
# Combine the encoded features into a list of tuples (each tuple represents a row of features)

y = list(cls)
# Convert the target variable "class" into a list

x_train, x_test, y_train, y_test = sklearn.model_selection.train_test_split(x, y, test_size=0.1)
# Split the data into training and testing sets; 10% of the data is set aside for testing

print(x_train, y_test)
# Print the training data (features) and the test data (target values) to see what they look like


[(3, 2, 0, 1, 0, 0), (3, 2, 1, 0, 1, 1), (2, 3, 2, 2, 2, 1), (1, 3, 2, 1, 0, 1), (1, 1, 3, 2, 1, 0), (1, 2, 1, 1, 0, 0), (2, 3, 2, 1, 2, 2), (1, 0, 3, 2, 2, 1), (1, 3, 3, 2, 0, 2), (1, 3, 2, 0, 0, 2), (2, 0, 1, 1, 0, 0), (1, 2, 3, 2, 2, 2), (3, 1, 2, 2, 2, 0), (2, 3, 1, 0, 0, 1), (2, 3, 3, 1, 0, 0), (0, 0, 3, 2, 0, 1), (1, 2, 0, 1, 0, 1), (0, 3, 0, 2, 0, 0), (2, 0, 3, 0, 0, 1), (1, 2, 3, 1, 1, 2), (1, 3, 2, 2, 1, 1), (2, 1, 1, 1, 2, 1), (0, 2, 3, 0, 0, 2), (0, 1, 0, 0, 2, 1), (2, 3, 1, 0, 1, 0), (1, 3, 3, 2, 2, 2), (0, 0, 2, 2, 1, 1), (2, 2, 1, 1, 2, 1), (0, 2, 2, 1, 2, 1), (1, 1, 2, 1, 1, 1), (3, 3, 1, 1, 1, 1), (0, 1, 0, 2, 0, 2), (0, 0, 2, 0, 2, 1), (0, 0, 0, 0, 0, 2), (2, 1, 3, 1, 0, 0), (0, 3, 0, 1, 1, 0), (2, 0, 3, 0, 2, 1), (0, 1, 2, 2, 0, 0), (3, 2, 0, 1, 1, 2), (0, 0, 0, 0, 0, 0), (1, 3, 3, 0, 1, 2), (1, 1, 0, 1, 0, 1), (0, 3, 1, 2, 1, 2), (2, 1, 0, 2, 0, 1), (0, 1, 3, 0, 0, 0), (0, 3, 1, 0, 2, 0), (3, 0, 3, 1, 1, 2), (3, 3, 3, 1, 1, 0), (2, 1, 3, 2, 2, 0), (0, 0, 3, 2, 2, 2),

In [132]:
model = KNeighborsClassifier(metric='euclidean', p=3, n_neighbors=9)
# Create a K-Nearest Neighbors (KNN) classifier with Euclidean distance, using 9 neighbors

model.fit(x_train, y_train)
# Train the KNN model using the training data

acc = model.score(x_test, y_test)
# Calculate the accuracy of the model on the test data

print(acc)
# Print the accuracy score to see how well the model performed

0.953757225433526


In [133]:
y_pred = model.predict(x_test) 

y_pred 

array([2, 2, 2, 3, 2, 0, 2, 0, 2, 2, 2, 0, 2, 2, 1, 2, 2, 0, 0, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2,
       2, 3, 0, 2, 2, 2, 2, 2, 2, 0, 2, 2, 0, 2, 2, 2, 0, 2, 2, 2, 2, 2,
       2, 2, 0, 2, 2, 2, 0, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 0, 2, 2, 0, 1,
       2, 2, 2, 2, 2, 1, 0, 2, 2, 2, 2, 2, 0, 2, 0, 2, 0, 2, 2, 2, 3, 2,
       2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 0, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 0, 0, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 0, 2, 2, 2, 2])

In [134]:
# Make predictions using the trained model
predicted = model.predict(x_test) 

# List of class names corresponding to the prediction labels
names = ["unnac", "acc", "good", "vgood"] 

# Iterate through each prediction
for x in range(len(predicted)): 
    # Print the predicted class, test data, and actual class
    print("predicted: ", names[predicted[x]], "Data:", x_test[x], "actual: ", names[y_test[x]]) 

    # Find the 9 nearest neighbors for the current test data
    n = model.kneighbors([x_test[x]], 9, True) 

# Print the nearest neighbors information
print("N: ", n)

predicted:  good Data: (2, 2, 2, 0, 1, 0) actual:  good
predicted:  good Data: (1, 0, 3, 2, 0, 1) actual:  good
predicted:  good Data: (2, 0, 1, 0, 0, 1) actual:  good
predicted:  vgood Data: (1, 0, 3, 1, 0, 0) actual:  vgood
predicted:  good Data: (0, 0, 2, 0, 1, 1) actual:  good
predicted:  unnac Data: (0, 1, 3, 1, 2, 0) actual:  unnac
predicted:  good Data: (1, 1, 1, 2, 0, 1) actual:  good
predicted:  unnac Data: (1, 1, 2, 2, 2, 2) actual:  unnac
predicted:  good Data: (2, 2, 2, 2, 2, 1) actual:  good
predicted:  good Data: (2, 3, 3, 2, 1, 1) actual:  good
predicted:  good Data: (3, 3, 0, 0, 2, 0) actual:  good
predicted:  unnac Data: (2, 3, 3, 2, 1, 2) actual:  unnac
predicted:  good Data: (0, 0, 0, 0, 2, 0) actual:  good
predicted:  good Data: (0, 1, 1, 0, 1, 2) actual:  good
predicted:  acc Data: (1, 1, 0, 1, 1, 0) actual:  acc
predicted:  good Data: (2, 2, 1, 0, 2, 2) actual:  good
predicted:  good Data: (3, 1, 0, 2, 2, 2) actual:  good
predicted:  unnac Data: (0, 0, 0, 2, 0, 2)

In [135]:
# Compute the confusion matrix to evaluate the classification performance
cm = confusion_matrix(y_test, y_pred) 

# Print the confusion matrix
print(cm) 

# Compute and print the accuracy score of the model
print(accuracy_score(y_test, y_pred))

[[ 27   0   5   0]
 [  1   3   0   0]
 [  1   0 132   0]
 [  1   0   0   3]]
0.953757225433526
